//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PurchasedItem
    {
        public long lng_PurchaseID { get; set; }
        public Nullable<long> lng_UserID { get; set; }
        public Nullable<long> lng_ProductID { get; set; }
        public Nullable<System.DateTime> dte_PurchasedDate { get; set; }
        public string str_Status { get; set; }
        public Nullable<int> lng_Quantity { get; set; }
        public Nullable<int> lng_Total_Price { get; set; }
    
        public virtual tbl_Product tbl_Product { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
