//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Product()
        {
            this.tbl_PurchasedItem = new HashSet<tbl_PurchasedItem>();
        }
    
        public long lng_ProductID { get; set; }
        public string str_Productname { get; set; }
        public string str_Imageurl { get; set; }
        public string str_ActivationStatus { get; set; }
        public Nullable<long> lng_CreatedBy { get; set; }
        public Nullable<System.DateTime> dte_CreatedDate { get; set; }
        public Nullable<long> lng_UpdatedBy { get; set; }
        public Nullable<System.DateTime> dte_UpdatedDate { get; set; }
        public Nullable<int> lng_Price { get; set; }
        public string str_Filename { get; set; }
    
        public virtual tbl_User tbl_User { get; set; }
        public virtual tbl_User tbl_User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PurchasedItem> tbl_PurchasedItem { get; set; }
    }
}
